# -*- coding: utf-8 -*-
from btfly.task import BaseTask

class Out(BaseTask):
    def execute(self, context):
        return ' '.join(self.get_values(context))

class CSV(BaseTask):
    def execute(self, context):
        return ','.join(self.get_values(context))

class Env(BaseTask):
    def add_options(self, parser):
        parser.add_argument(
            '-E', '--env-name', default='BTFLY_HOSTS',
            help='Specify a name of environment variable to be output.'
        )

    def execute(self, context):
        values = self.get_values(context)
        env_name = context.options.get('env_name') or 'BTFLY_HOSTS'
        return "%s=(%s)" % (env_name, ' '.join(values))
# eval `BTFLY_ENV=production btfly --tags web --field ip env`
# --> BTFLY_HOSTS=(127.0.0.1 192.168.1.2)
# % btfly_foreach; do ssh $i uptime; done

class Hosts(BaseTask):
    def execute(self, context):
        hosts = context.hosts_manager.hosts(
            tags=context.options.get('tags'),
            statuses=context.options.get('statuses'),
        )
        # TODO: line separator compatibility (set in conf.yaml ?)
        s = """
# Generated by btfly
"""
        for host in hosts:
            s += "%s %s\n" % (host.ip, host.name)
        return s.strip()

def register(manager):
    """
    This function is called when this plugin is loaded.
    """
    manager.register_task(Out('out', "output as text."))
    manager.register_task(CSV('csv', "output as CSV."))
    manager.register_task(Env('env', "output as sh environment."))
    manager.register_task(Hosts('hosts', "output as /etc/hosts format."))
